- name: Installing shorewall Package
  apt: name=shorewall state=present
- name: Installing shorewall6 Package
  apt: name=shorewall6 state=present
- name: Installing xtables-addons
  apt: name=xtables-addons-dkms state=present

- template: src=templates/interfaces.v4 dest=/etc/shorewall/interfaces 
- template: src=templates/policy.v4 dest=/etc/shorewall/policy
- template: src=templates/zones.v4 dest=/etc/shorewall/zones
- template: src=templates/rules.v4 dest=/etc/shorewall/rules
- name: Enable IPv4 Forwarding 
  lineinfile: dest=/etc/shorewall/shorewall.conf regexp=^IP_FORWARDING= line=IP_FORWARDING=Yes
- name: Do not Log martions
  lineinfile: dest=/etc/shorewall/shorewall.conf regexp=^LOG_MARTIANS= line=LOG_MARTIANS=No
- name: Enable shorewall on Boot
  lineinfile: dest=/etc/default/shorewall regexp=^startup= line=startup=1  

- template: src=templates/interfaces.v6 dest=/etc/shorewall6/interfaces
- template: src=templates/policy.v6 dest=/etc/shorewall6/policy
- template: src=templates/zones.v6 dest=/etc/shorewall6/zones
- template: src=templates/rules.v6 dest=/etc/shorewall6/rules
- name: Enable IPv6 Forwarding
  lineinfile: dest=/etc/shorewall6/shorewall6.conf regexp=^IP_FORWARDING= line=IP_FORWARDING=Yes
- name: Enable shorewall6 on Boot
  lineinfile: dest=/etc/default/shorewall6 regexp=^startup= line=startup=1

