---
galaxy_info:
  author: kaleng
  description: secure ssh config
  license: GPLv3
  min_ansible_version: 1.8
  platforms:
  - name: Debian
    versions:
    - wheezy
    - jessie
  - name: Archlinux
dependencies: []
  
