---
- hosts: servers
  roles:
    - common
    - sas_util
    - fastd-exit
    - create_admin_users
    - securessh
    - check_mk_agent
    - smartmontools
    - backuppc
    - tap-router-exit
    - ccc_network
    - shorewall_masquerade
    - ip_on_boot
    - shorewall
    - openvpn-exit   
    - kbu.backbone
