---
# tasks file for secure-secure-shell

- name: template sshd config wheezy
  template:
    src: sshd_config_wheezy
    dest: '/etc/ssh/sshd_config'
    mode: '0644'
    owner: root
    group: root
    validate: '/usr/sbin/sshd -t -f %s'
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy'
  notify:
  - sshrestart

- name: template sshd config jessie
  template:
    src: sshd_config_jessie
    dest: '/etc/ssh/sshd_config'
    mode: '0644'
    owner: root
    group: root
    validate: '/usr/sbin/sshd -t -f %s'
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'
  notify:
  - sshrestart

- name: template sshd config Archlinux
  template:
    src: sshd_config_archlinux
    dest: '/etc/ssh/sshd_config'
    mode: '0644'
    owner: root
    group: root
    validate: '/usr/sbin/sshd -t -f %s'
  when: ansible_distribution == 'Archlinux'
  notify:
  - sshrestart_arch

- name: delete dsa/ecdsa keys
  file:
    dest: '{{ item }}'
    state: absent
  with_items:
  - '/etc/ssh/ssh_host_dsa_key'
  - '/etc/ssh/ssh_host_dsa_key.pub'
  - '/etc/ssh/ssh_host_ecdsa_key'
  - '/etc/ssh/ssh_host_ecdsa_key.pub'

- include: rsa.yml
