---

- include: debian.yml
  when: ansible_distribution == "Debian"

- include: openwrt.yml
  when: ansible_distribution == "OpenWrt"

- include: archlinux.yml
  when: ansible_distribution == "Archlinux"

- name: add check_mk_agent_user
  user:
    name: "{{ check_mk_agent_user }}"
    shell: "/bin/bash"
    state: present

- name: add check_mk_agent_ssh_keys with sudo
  authorized_key:
    user: "{{ check_mk_agent_user }}"
    key: "{{ item }}"
    key_options: 'command="/usr/bin/sudo /usr/bin/check_mk_agent"'
    state: present
  with_items: check_mk_agent_ssh_keys

- name: add check_mk_agent_user sudoers line
  lineinfile:
    dest: /etc/sudoers
    line: "{{ check_mk_agent_user }} ALL=NOPASSWD: /usr/bin/check_mk_agent"
    state: present

