---
- fail: msg="openwrt.yml called on non OpenWrt system"
  when: ansible_distribution != "OpenWrt"

- name: install packages on OpenWrt
  opkg: name={{ item }} state=present
  with_items:
  - sudo
  - openssh-sftp-server
  - shadow-useradd
  - shadow-usermod
  - python-openssl
  - bash

- include: copy_agent.yml
